// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPEX4PeO7BtTiiHn4kB1Z23az0clTJJaQ',
    appId: '1:1078043149313:web:f5fcf86eb9b0fc30d76c00',
    messagingSenderId: '1078043149313',
    projectId: 'talent-connect-70ae6',
    authDomain: 'talent-connect-70ae6.firebaseapp.com',
    databaseURL: 'https://talent-connect-70ae6.firebaseio.com',
    storageBucket: 'talent-connect-70ae6.appspot.com',
    measurementId: 'G-0W82F14PLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp5DBKXLl6Dg4bM736HG7aLZhayrkaeBU',
    appId: '1:1078043149313:android:bc8cee9e536a1084d76c00',
    messagingSenderId: '1078043149313',
    projectId: 'talent-connect-70ae6',
    databaseURL: 'https://talent-connect-70ae6.firebaseio.com',
    storageBucket: 'talent-connect-70ae6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQWf_p8eqVgW4wSx8yz_G6p3HbJyucjw0',
    appId: '1:1078043149313:ios:84fbdbae45255773d76c00',
    messagingSenderId: '1078043149313',
    projectId: 'talent-connect-70ae6',
    databaseURL: 'https://talent-connect-70ae6.firebaseio.com',
    storageBucket: 'talent-connect-70ae6.appspot.com',
    androidClientId: '1078043149313-n45qfjh0gebmllfartqndmdu0m1chkti.apps.googleusercontent.com',
    iosClientId: '1078043149313-6qsfjjtb5hnmt5mtltihnodgj5uqaqqn.apps.googleusercontent.com',
    iosBundleId: 'com.example.talentconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQWf_p8eqVgW4wSx8yz_G6p3HbJyucjw0',
    appId: '1:1078043149313:ios:84fbdbae45255773d76c00',
    messagingSenderId: '1078043149313',
    projectId: 'talent-connect-70ae6',
    databaseURL: 'https://talent-connect-70ae6.firebaseio.com',
    storageBucket: 'talent-connect-70ae6.appspot.com',
    androidClientId: '1078043149313-n45qfjh0gebmllfartqndmdu0m1chkti.apps.googleusercontent.com',
    iosClientId: '1078043149313-6qsfjjtb5hnmt5mtltihnodgj5uqaqqn.apps.googleusercontent.com',
    iosBundleId: 'com.example.talentconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPEX4PeO7BtTiiHn4kB1Z23az0clTJJaQ',
    appId: '1:1078043149313:web:ff796991b771e8d7d76c00',
    messagingSenderId: '1078043149313',
    projectId: 'talent-connect-70ae6',
    authDomain: 'talent-connect-70ae6.firebaseapp.com',
    databaseURL: 'https://talent-connect-70ae6.firebaseio.com',
    storageBucket: 'talent-connect-70ae6.appspot.com',
    measurementId: 'G-H12XPTE6BL',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCPEX4PeO7BtTiiHn4kB1Z23az0clTJJaQ',
    appId: '1:1078043149313:web:7ac24fcfd74dead9d76c00',
    messagingSenderId: '1078043149313',
    projectId: 'talent-connect-70ae6',
    authDomain: 'talent-connect-70ae6.firebaseapp.com',
    databaseURL: 'https://talent-connect-70ae6.firebaseio.com',
    storageBucket: 'talent-connect-70ae6.appspot.com',
    measurementId: 'G-WC8FRMTLPJ',
  );
}
